export const issuePageConstants = {
  GET_ISSUE_REQUEST: "GET_ISSUE_REQUEST",
  GET_ISSUE_SUCCESS: "GET_ISSUE_SUCCESS",
  GET_ISSUE_FAIL: "GET_ISSUE_FAIL",
  UPDATE_CURRENT_PAGE: "UPDATE_CURRENT_PAGE",
};
