export const issueDetailsConstants = {
  // get issue details
  GET_ISSUE_DETAILS_REQUEST: "GET_ISSUE_DETAILS_REQUEST",
  GET_ISSUE_DETAILS_SUCCESS: "GET_ISSUE_DETAILS_SUCCESS",
  GET_ISSUE_DETAILS_FAIL: "GET_ISSUE_DETAILS_FAIL",

  // get comments
  GET_COMMENTS_REQUEST: "GET_COMMENTS_REQUEST",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
  GET_COMMENTS_FAIL: "GET_COMMENTS_FAIL",
};
