export const issueDetailsConstants = {
  GET_ISSUE_DETAILS_REQUEST: "GET_ISSUE_DETAILS_REQUEST",
  GET_ISSUE_DETAILS_SUCCESS: "GET_ISSUE_DETAILS_SUCCESS",
  GET_ISSUE_DETAILS_FAIL: "GET_ISSUE_DETAILS_FAIL",
};
